%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFeZQAV",
    "SessionName": "S-036331",
    "SessionDate": "2022-08-13",
    "Weekday": "Saturday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036331",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFeaQAF",
    "SessionName": "S-036332",
    "SessionDate": "2022-08-15",
    "Weekday": "Monday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036332",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFebQAF",
    "SessionName": "S-036333",
    "SessionDate": "2022-08-16",
    "Weekday": "Tuesday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036333",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFecQAF",
    "SessionName": "S-036334",
    "SessionDate": "2022-08-17",
    "Weekday": "Wednesday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036334",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFedQAF",
    "SessionName": "S-036335",
    "SessionDate": "2022-08-18",
    "Weekday": "Thursday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036335",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFeeQAF",
    "SessionName": "S-036336",
    "SessionDate": "2022-08-19",
    "Weekday": "Friday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036336",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFefQAF",
    "SessionName": "S-036337",
    "SessionDate": "2022-08-20",
    "Weekday": "Saturday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036337",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFegQAF",
    "SessionName": "S-036338",
    "SessionDate": "2022-08-22",
    "Weekday": "Monday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036338",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFehQAF",
    "SessionName": "S-036339",
    "SessionDate": "2022-08-23",
    "Weekday": "Tuesday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036339",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  },
  {
    "TeamSeasonId": "a0q1T00000BLSdwQAH",
    "SessionId": "a0p1T00000FcFeiQAF",
    "SessionName": "S-036340",
    "SessionDate": "2022-08-24",
    "Weekday": "Wednesday",
    "SessionTopic": "",
    "IsDeleted": "false",
    "SessionName": "S-036340",
    "StudentsAbsent": "0.0",
    "StudentsPresent": "0.0",
    "AttendancePercentage": null,
    "TeamSeasonName": "ER Taylor Select-2022-2023",
    "TeamName": "ER Taylor Select",
    "SeasonName": "2022-2023",
    "Region": "San Francisco Crocker",
    "ProgramType": "Select",
    "UsesHeadcount": "false"
  }
])