%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NT4p5QAD",
    "SeasonName": "",
    "TotalNoOfPlayers": "2.0",
    "TeamSeasonName": "Davidson Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008JxkFQAS",
    "TeamName": "",
    "SchoolSite": "Davidson Middle School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NT4p6QAD",
    "SeasonName": "",
    "TotalNoOfPlayers": "6.0",
    "TeamSeasonName": "Laurel Dell Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008JxkVQAS",
    "TeamName": "",
    "SchoolSite": "Laurel Dell Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NT4p7QAD",
    "SeasonName": "",
    "TotalNoOfPlayers": "1.0",
    "TeamSeasonName": "San Pedro Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008Jxl3QAC",
    "TeamName": "",
    "SchoolSite": "San Pedro Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "8.0",
    "TeamSeasonName": "Short Girls-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009q9hwQAA",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "90.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "15.0",
    "TeamSeasonName": "Howard Boys-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009q9iOQAQ",
    "TeamName": "",
    "SchoolSite": "Howard Elementary School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NSu95QAD",
    "SeasonName": "",
    "TotalNoOfPlayers": "15.0",
    "TeamSeasonName": "Howard Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008JtuMQAS",
    "TeamName": "",
    "SchoolSite": "Howard Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NT4pAQAT",
    "SeasonName": "",
    "TotalNoOfPlayers": "8.0",
    "TeamSeasonName": "Short Girls-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008JyejQAC",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NT4pAQAT",
    "SeasonName": "",
    "TotalNoOfPlayers": "15.0",
    "TeamSeasonName": "Short Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008JyekQAC",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "14.0",
    "TeamSeasonName": "ASCEND Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ougnQAA",
    "TeamName": "",
    "SchoolSite": "ASCEND Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "2.0",
    "TeamSeasonName": "Davidson Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouh6QAA",
    "TeamName": "",
    "SchoolSite": "Davidson Middle School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "19.0",
    "TeamSeasonName": "Howard Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouhdQAA",
    "TeamName": "",
    "SchoolSite": "Howard Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "6.0",
    "TeamSeasonName": "Laurel Dell Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouhvQAA",
    "TeamName": "",
    "SchoolSite": "Laurel Dell Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "1.0",
    "TeamSeasonName": "San Pedro Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouieQAA",
    "TeamName": "",
    "SchoolSite": "San Pedro Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "19.0",
    "TeamSeasonName": "Short Boys-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouinQAA",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "10.0",
    "TeamSeasonName": "Short Girls-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ouioQAA",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "0.0",
    "TeamSeasonName": "Short Juniors-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ovGyQAI",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2020-01-01",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "2.0",
    "TeamSeasonName": "Short Juniors-2020 Spring",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009ovH3QAI",
    "TeamName": "",
    "SchoolSite": "Short Elementary School",
    "SeasonEndDate": "2020-05-31"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "47.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "0.0",
    "TeamSeasonName": "Howard Coed-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009pzTYQAY",
    "TeamName": "",
    "SchoolSite": "Howard Elementary School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "15.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "2.0",
    "TeamSeasonName": "Davidson Boys-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009pzTtQAI",
    "TeamName": "",
    "SchoolSite": "Davidson Middle School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2019-08-12",
    "TotalNoOfSessions": "0.0",
    "CoachWriting": "",
    "Partnership": "a0n1T00000NSoeeQAD",
    "SeasonName": "",
    "TotalNoOfPlayers": "11.0",
    "TeamSeasonName": "ASCEND Boys-2019 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000008Jt3NQAS",
    "TeamName": "",
    "SchoolSite": "ASCEND Elementary School",
    "SeasonEndDate": "2019-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "30.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "14.0",
    "TeamSeasonName": "ASCEND Boys-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009q9hfQAA",
    "TeamName": "",
    "SchoolSite": "ASCEND Elementary School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "30.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "6.0",
    "TeamSeasonName": "Laurel Dell Boys-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009q9hnQAA",
    "TeamName": "",
    "SchoolSite": "Laurel Dell Elementary School",
    "SeasonEndDate": "2020-12-20"
  },
  {
    "SeasonStartDate": "2020-08-12",
    "TotalNoOfSessions": "30.0",
    "CoachWriting": "",
    "Partnership": "",
    "SeasonName": "",
    "TotalNoOfPlayers": "1.0",
    "TeamSeasonName": "San Pedro Boys-2020 Fall",
    "CoachSoccer": "",
    "TeamSeasonId": "a0q1T000009q9hoQAA",
    "TeamName": "",
    "SchoolSite": "San Pedro Elementary School",
    "SeasonEndDate": "2020-12-20"
  }
])