[
  {
    "Parent_Phone_03__c": null,
    "AccountId": "0015000002HvvVxAAJ",
    "Email": null,
    "Reduced_Price_Lunch__c": null,
    "type": "Contact",
    "Data_Release__c": "true",
    "Emergency_Contact_Name_Phone_02__c": null,
    "Second_Emergency_Phone_01__c": null,
    "Volunteer_for_this_Program_Parent__c": null,
    "Emergency_Contact_Permission_to_Pick_Up__c": null,
    "Second_Emergency_Contact_Name__c": null,
    "Liability__c": "true",
    "Parent_Home_Language__c": null,
    "Second_Emergency_Phone_02__c": null,
    "Ethnicity__c": null,
    "Parent_English_Fluency__c": null,
    "Parent_Last_Name__c": "Lalila Siquinajay",
    "Second_Emergency_Permission_to_Pick_Up__c": null,
    "Gender__c": null,
    "MailingCity": null,
    "Birthdate": "2010-09-07",
    "Allergies__c": null,
    "Parent_Email_Address__c": null,
    "Emergency_Contact_Name_Phone_03__c": null,
    "Id": "0031T00004CZca4QAD",
    "LastName": "Puz Delton",
    "School_Attending__c": null,
    "MailingStreet": null,
    "Parent_Phone_01__c": "510-395-3624",
    "Second_Emergency_Phone_03__c": null,
    "Contact_Type__c": "SCORES Student",
    "MailingCountry": null,
    "Parent_Other_Language__c": null,
    "MailingState": null,
    "Level__c": null,
    "MailingPostalCode": null,
    "RecordTypeId": "01250000000VBbXAAW",
    "Grade__c": null,
    "Emergency_Contact_Relationship_to_Child__c": null,
    "Parent_Phone_02__c": null,
    "Permission_to_Commute_Alone__c": null,
    "Parent_Relationship_to_Child__c": null,
    "FirstName": "Alexander",
    "MiddleName": null,
    "External_Student_DB__c": null,
    "Parent_First_Name__c": "Doris",
    "Emergency_Contact_Name_Phone_01__c": null,
    "Second_Emerg_Contact_Relationship_Child__c": null,
    "Media_Release__c": "true",
    "HomePhone": null,
    "Emergency_Contact_Name__c": null,
    "External_Student_ID__c": null
  }
]