%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([{
	"Id": "0031T00004E2ULBQA3",
	"ContactType": "SCORES Student",
	"ContactRecordType": "01250000000VBbXAAW",
	"FirstName": "Ray'shonte",
	"MiddleName": "",
	"LastName": "Rogers",
	"SchoolSiteId": "0011T00002Vrpl7QAB",
	"SchoolName": "",
	"PersonalEmail": "",
	"HomePhone": "",
	"Birthdate": "2010-08-20",
	"Gender": "Female",
	"Grade": "5th",
	"K12GradeLevel": "",
	"Ethnicity": "African American",
	"PermissiontoCommuteAlone": "",
	"ReducedPriceLunch": "",
	"Allergies": "",
	"ExternalStudentId": "46890847",
	"ExternalStudentIdSource": "DCYF",
	"ParentFName": "",
	"ParentLName": "",
	"ParentEmail": "",
	"Relationship": "",
	"ParentPhone1": "",
	"ParentPhone2": "",
	"ParentPhone3": "",
	"MailingStreet": "1915 Sutter St",
	"MailingCity": "San Francisco",
	"MailingState": "CA",
	"MailingZip": "94115",
	"MailingCountry": "",
	"ParentEnglishFluency": "",
	"ParentHomeLang": "",
	"OtherLang": "",
	"Volunteer": "",
	"Emergency_Contact_Name": "",
	"Emergency_Contact_Relationship": "",
	"Emergency_Contact_Phone1": "",
	"Emergency_Contact_Phone2": "",
	"Emergency_Contact_Phone3": "",
	"Emergency_Contact_Permission_to_Pickup_child": "",
	"Second_Emergency_Contact_Name": "",
	"Second_Emergency_Contact_Relationship": "",
	"Second_Emergency_Contact_Phone1": "",
	"Second_Emergency_Contact_Phone2": "",
	"Second_Emergency_Contact_Phone3": "",
	"Second_Emergency_Contact_Permission_to_Pickup_child": "",
	"LiabilityWaiver": "true",
	"MediaReleaseWaiver": "true",
	"DataReleaseWaiver": "true"
}])