[
  {
    "Parent_Phone_03__c": null,
    "AccountId": "0011T00002Vrpl7QAB",
    "Email": null,
    "Reduced_Price_Lunch__c": null,
    "type": "Contact",
    "Data_Release__c": "true",
    "Emergency_Contact_Name_Phone_02__c": null,
    "Second_Emergency_Phone_01__c": null,
    "Volunteer_for_this_Program_Parent__c": null,
    "Emergency_Contact_Permission_to_Pick_Up__c": null,
    "Second_Emergency_Contact_Name__c": null,
    "Liability__c": "true",
    "Parent_Home_Language__c": null,
    "Second_Emergency_Phone_02__c": null,
    "Ethnicity__c": "African American",
    "Parent_English_Fluency__c": null,
    "Parent_Last_Name__c": null,
    "Second_Emergency_Permission_to_Pick_Up__c": null,
    "Gender__c": "Female",
    "MailingCity": "San Francisco",
    "Birthdate": "2010-08-20",
    "Allergies__c": null,
    "Parent_Email_Address__c": null,
    "Emergency_Contact_Name_Phone_03__c": null,
    "Id": "0031T00004E2ULBQA3",
    "LastName": "Rogers",
    "School_Attending__c": null,
    "MailingStreet": "1915 Sutter St",
    "Parent_Phone_01__c": null,
    "Second_Emergency_Phone_03__c": null,
    "Contact_Type__c": "SCORES Student",
    "MailingCountry": null,
    "Parent_Other_Language__c": null,
    "MailingState": "CA",
    "Level__c": null,
    "MailingPostalCode": "94115",
    "RecordTypeId": "01250000000VBbXAAW",
    "Grade__c": "5th",
    "Emergency_Contact_Relationship_to_Child__c": null,
    "Parent_Phone_02__c": null,
    "Permission_to_Commute_Alone__c": null,
    "Parent_Relationship_to_Child__c": null,
    "FirstName": "Ray'shonte",
    "MiddleName": null,
    "External_Student_DB__c": "DCYF",
    "Parent_First_Name__c": null,
    "Emergency_Contact_Name_Phone_01__c": null,
    "Second_Emerg_Contact_Relationship_Child__c": null,
    "Media_Release__c": "true",
    "HomePhone": null,
    "Emergency_Contact_Name__c": null,
    "External_Student_ID__c": "46890847"
  }
]