%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Id": "0031T00004CZca4QAD",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Alexander",
    "MiddleName": "",
    "LastName": "Puz Delton",
    "SchoolSiteId": "0015000002HvvVxAAJ",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2010-09-07",
    "Gender": "",
    "Grade": "",
    "K12GradeLevel": "",
    "Ethnicity": "",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "",
    "ParentFName": "Doris",
    "ParentLName": "Lalila Siquinajay",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "510-395-3624",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "",
    "MailingCountry": "",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004CZcaDQAT",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Edgar Cayetano",
    "MiddleName": "",
    "LastName": "Puz",
    "SchoolSiteId": "0015000002HvvVxAAJ",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2009-07-02",
    "Gender": "",
    "Grade": "",
    "K12GradeLevel": "",
    "Ethnicity": "",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "",
    "ParentFName": "Doris",
    "ParentLName": "Lalila Siquinajay",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "510-395-3624",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "",
    "MailingCountry": "",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  }
])