{
  "searchRecords": [
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvVlAAJ",
        "Email": null,
        "Parent_Phone_01__c": "(415)964- 6867",
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "MailingState": "California",
        "Name": "A. Giovany Uc",
        "Level__c": null,
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "MailingPostalCode": "94109",
        "RecordTypeId": "01250000000VBbXAAW",
        "Zip_First_Five_Digits__c": "94109",
        "Grade__c": "6th",
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Relationship_to_Child__c": "Uncle",
        "Parent_Phone_02__c": "(415)350- 6662",
        "Second_Emergency_Contact_Name__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "A. Giovany",
        "Parent_Home_Language__c": "Spanish",
        "Ethnicity__c": "Hispanic/Latino",
        "Parent_Last_Name__c": "Perez",
        "Gender__c": "Male",
        "MailingAddress": {
          "country": null,
          "city": "San Francisco",
          "countryCode": null,
          "street": "1029 Geary St",
          "latitude": 37.785563,
          "postalCode": "94109",
          "geocodeAccuracy": "Address",
          "stateCode": null,
          "state": "California",
          "longitude": -122.420304
        },
        "MailingCity": "San Francisco",
        "MiddleName": null,
        "Birthdate": "2009-01-01",
        "Parent_First_Name__c": "Neldy",
        "Allergies__c": null,
        "Emergency_Contact_Name_Phone_01__c": "(415)533- 6852",
        "HomePhone": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name__c": "Randy Perez",
        "External_Student_ID__c": null,
        "Id": "0031T00003d3qWfQAI",
        "LastName": "Uc",
        "School_Attending__c": null,
        "MailingStreet": "1029 Geary St"
      },
      "searchRecordMetadata": null
    }
  ],
  "queryId": "1qmie2ix0knul",
  "searchResultsMetadata": null
}