{
  "searchRecords": [
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvVlAAJ",
        "Email": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "Spanish",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latino",
        "Parent_English_Fluency__c": "No",
        "Parent_Last_Name__c": "Perez",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Male",
        "MailingCity": "San Francisco",
        "Birthdate": "2009-01-01",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00003d3qWfQAI",
        "LastName": "Uc",
        "School_Attending__c": null,
        "MailingStreet": "1029 Geary St",
        "Parent_Phone_01__c": "(415)964- 6867",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Parent_Other_Language__c": null,
        "MailingState": "California",
        "Level__c": null,
        "MailingPostalCode": "94109",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "6th",
        "Emergency_Contact_Relationship_to_Child__c": "Uncle",
        "Parent_Phone_02__c": "(415)350- 6662",
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "A. Giovany",
        "MiddleName": null,
        "External_Student_DB__c": null,
        "Parent_First_Name__c": "Neldy",
        "Emergency_Contact_Name_Phone_01__c": "(415)533- 6852",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "Randy Perez",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    }
  ],
  "queryId": "12yjcgv7en7co",
  "searchResultsMetadata": null
}