%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Id": "0031T000049b9P7QAI",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Ariana",
    "MiddleName": "",
    "LastName": "Gutierrez",
    "SchoolSiteId": "0015000002HvvWCAAZ",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2008-04-14",
    "Gender": "Female",
    "Grade": "6th",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latino",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "Yes",
    "Allergies": "none",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "",
    "ParentFName": "Sandra",
    "ParentLName": "Gutierrez",
    "ParentEmail": "deserttransport@yahoo.com",
    "Relationship": "Parent",
    "ParentPhone1": "7602214386",
    "ParentPhone2": "4153398813",
    "ParentPhone3": "",
    "MailingStreet": "75 Canal Street Apt. C3",
    "MailingCity": "San Rafael",
    "MailingState": "CA",
    "MailingZip": "94901",
    "MailingCountry": "",
    "ParentEnglishFluency": "Yes",
    "ParentHomeLang": "Spanish",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "Irma del Toro",
    "Emergency_Contact_Relationship": "Aunt",
    "Emergency_Contact_Phone1": "4155598641",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "Mariana Castro-Olivares",
    "Second_Emergency_Contact_Relationship": "Family Friend",
    "Second_Emergency_Contact_Phone1": "5107349201",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  }
])