[
  {
    "Parent_Phone_03__c": null,
    "AccountId": "0015000002HvvWCAAZ",
    "Email": null,
    "Reduced_Price_Lunch__c": "Yes",
    "type": "Contact",
    "Data_Release__c": "true",
    "Emergency_Contact_Name_Phone_02__c": null,
    "Second_Emergency_Phone_01__c": "5107349201",
    "Volunteer_for_this_Program_Parent__c": null,
    "Emergency_Contact_Permission_to_Pick_Up__c": null,
    "Second_Emergency_Contact_Name__c": "Mariana Castro-Olivares",
    "Liability__c": "true",
    "Parent_Home_Language__c": "Spanish",
    "Second_Emergency_Phone_02__c": null,
    "Ethnicity__c": "Hispanic/Latino",
    "Parent_English_Fluency__c": "Yes",
    "Parent_Last_Name__c": "Gutierrez",
    "Second_Emergency_Permission_to_Pick_Up__c": null,
    "Gender__c": "Female",
    "MailingCity": "San Rafael",
    "Birthdate": "2008-04-14",
    "Allergies__c": "none",
    "Parent_Email_Address__c": "deserttransport@yahoo.com",
    "Emergency_Contact_Name_Phone_03__c": null,
    "Id": "0031T000049b9P7QAI",
    "LastName": "Gutierrez",
    "School_Attending__c": null,
    "MailingStreet": "75 Canal Street Apt. C3",
    "Parent_Phone_01__c": "7602214386",
    "Second_Emergency_Phone_03__c": null,
    "Contact_Type__c": "SCORES Student",
    "MailingCountry": null,
    "Parent_Other_Language__c": null,
    "MailingState": "CA",
    "Level__c": null,
    "MailingPostalCode": "94901",
    "RecordTypeId": "01250000000VBbXAAW",
    "Grade__c": "6th",
    "Emergency_Contact_Relationship_to_Child__c": "Aunt",
    "Parent_Phone_02__c": "4153398813",
    "Permission_to_Commute_Alone__c": null,
    "Parent_Relationship_to_Child__c": "Parent",
    "FirstName": "Ariana",
    "MiddleName": null,
    "External_Student_DB__c": null,
    "Parent_First_Name__c": "Sandra",
    "Emergency_Contact_Name_Phone_01__c": "4155598641",
    "Second_Emerg_Contact_Relationship_Child__c": "Family Friend",
    "Media_Release__c": "true",
    "HomePhone": null,
    "Emergency_Contact_Name__c": "Irma del Toro",
    "External_Student_ID__c": null
  }
]