%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Id": "0031T00004DO9DVQA1",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Hernandez Deras",
    "MiddleName": "",
    "LastName": "Ariana",
    "SchoolSiteId": "0011T00002V6j1OQAR",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2011-07-15",
    "Gender": "",
    "Grade": "",
    "K12GradeLevel": "",
    "Ethnicity": "",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "",
    "ParentFName": "Jasmine",
    "ParentLName": "",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "510-434-6317",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "",
    "MailingCountry": "",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T000049b9P7QAI",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Ariana",
    "MiddleName": "",
    "LastName": "Gutierrez",
    "SchoolSiteId": "0015000002HvvWCAAZ",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2008-04-14",
    "Gender": "Female",
    "Grade": "6th",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latino",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "Yes",
    "Allergies": "none",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "",
    "ParentFName": "Sandra",
    "ParentLName": "Gutierrez",
    "ParentEmail": "deserttransport@yahoo.com",
    "Relationship": "Parent",
    "ParentPhone1": "7602214386",
    "ParentPhone2": "4153398813",
    "ParentPhone3": "",
    "MailingStreet": "75 Canal Street Apt. C3",
    "MailingCity": "San Rafael",
    "MailingState": "CA",
    "MailingZip": "94901",
    "MailingCountry": "",
    "ParentEnglishFluency": "Yes",
    "ParentHomeLang": "Spanish",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "Irma del Toro",
    "Emergency_Contact_Relationship": "Aunt",
    "Emergency_Contact_Phone1": "4155598641",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "Mariana Castro-Olivares",
    "Second_Emergency_Contact_Relationship": "Family Friend",
    "Second_Emergency_Contact_Phone1": "5107349201",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00003UDurTQAT",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Ariana",
    "MiddleName": "",
    "LastName": "Hernandez deras",
    "SchoolSiteId": "0015000002HvvWKAAZ",
    "SchoolName": "",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2011-07-15",
    "Gender": "Female",
    "Grade": "3rd",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latino",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "Yes",
    "Allergies": "",
    "ExternalStudentId": "48818555",
    "ExternalStudentIdSource": "OFCY",
    "ParentFName": "Jasmin",
    "ParentLName": "Deras",
    "ParentEmail": "",
    "Relationship": "Parent",
    "ParentPhone1": "",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "1575 fir ave",
    "MailingCity": "San leandro",
    "MailingState": "Ca",
    "MailingZip": "94601",
    "MailingCountry": "",
    "ParentEnglishFluency": "Yes",
    "ParentHomeLang": "Spanish",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "May Hernandez",
    "Emergency_Contact_Relationship": "Father",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "false",
    "MediaReleaseWaiver": "false",
    "DataReleaseWaiver": "false"
  }
])