%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Id": "0031T00004RX5a7QAD",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "test",
    "MiddleName": "",
    "LastName": "test",
    "Region": "San Francisco Crocker",
    "SchoolSiteId": "0015000002HvvVwAAJ",
    "SchoolName": "Bridges Academy Elementary School",
    "PersonalEmail": "test@gmail.com",
    "HomePhone": "",
    "Birthdate": "2002-10-09",
    "Gender": "Male",
    "Grade": "4th",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latinx",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "No",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "test",
    "ParentLName": "test",
    "ParentEmail": "ignacio.a.lopezscala@gmail.com",
    "Relationship": "Parent",
    "ParentPhone1": "7894561231",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "Spanish",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "test",
    "Emergency_Contact_Relationship": "Legal Guardian",
    "Emergency_Contact_Phone1": "7894561231",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004VBidtQAD",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "test",
    "MiddleName": "",
    "LastName": "test",
    "Region": "Oakland",
    "SchoolSiteId": "0015000002HvvWQAAZ",
    "SchoolName": "puffy",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2023-04-02",
    "Gender": "Male",
    "Grade": "5th",
    "K12GradeLevel": "",
    "Ethnicity": "Caucasian",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "No",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "Friendly",
    "ParentLName": "Friend",
    "ParentEmail": "sdfkhjsdf@sj.com",
    "Relationship": "Legal Guardian",
    "ParentPhone1": "2672626622",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "Chinese (incl. Cantonese, Mandarin, other Chinese languages)",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "refriend friend",
    "Emergency_Contact_Relationship": "Legal Guardian",
    "Emergency_Contact_Phone1": "3434343434",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004S5yN4QAJ",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "test",
    "MiddleName": "",
    "LastName": "test",
    "Region": "Oakland",
    "SchoolSiteId": "0015000002HvvWRAAZ",
    "SchoolName": "MLK",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2011-12-29",
    "Gender": "Male",
    "Grade": "3rd",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latinx",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "Yes",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "test 12",
    "ParentLName": "test12",
    "ParentEmail": "",
    "Relationship": "Parent",
    "ParentPhone1": "4155325763",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "English",
    "OtherLang": "",
    "Volunteer": "Yes",
    "Emergency_Contact_Name": "test",
    "Emergency_Contact_Relationship": "Grandparent",
    "Emergency_Contact_Phone1": "4152525252",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004TxcXuQAJ",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "User test",
    "MiddleName": "",
    "LastName": "testing",
    "Region": "Hayward",
    "SchoolSiteId": "0015000002HvvWaAAJ",
    "SchoolName": "Bret",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2009-02-10",
    "Gender": "Non-Binary",
    "Grade": "4th",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latinx",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "No",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "User test",
    "ParentLName": "User test",
    "ParentEmail": "testing@gmail.com",
    "Relationship": "Parent",
    "ParentPhone1": "4155555555",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "Spanish",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "User test",
    "Emergency_Contact_Relationship": "Grandparent",
    "Emergency_Contact_Phone1": "4155555555",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004UMvefQAD",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VAMzAAO",
    "FirstName": "Student009",
    "MiddleName": "",
    "LastName": "Test009",
    "Region": "",
    "SchoolSiteId": "0011T00002lM2T9QAK",
    "SchoolName": "Civic Center",
    "PersonalEmail": "test009@scores.org",
    "HomePhone": "",
    "Birthdate": "",
    "Gender": "",
    "Grade": "",
    "K12GradeLevel": "",
    "Ethnicity": "",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "",
    "ParentLName": "",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "",
    "MailingCountry": "",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004S5LKCQA3",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "testingModa",
    "MiddleName": "",
    "LastName": "testingModa",
    "Region": "San Francisco Civic Center",
    "SchoolSiteId": "0015000002HvvW3AAJ",
    "SchoolName": "John",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2011-10-26",
    "Gender": "Unknown",
    "Grade": "3rd",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latinx",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "No",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "testingModal",
    "ParentLName": "testingModal",
    "ParentEmail": "testing@hotmail.com",
    "Relationship": "Parent",
    "ParentPhone1": "4155551234",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "English",
    "OtherLang": "",
    "Volunteer": "No",
    "Emergency_Contact_Name": "testingModal",
    "Emergency_Contact_Relationship": "Legal Guardian",
    "Emergency_Contact_Phone1": "7894561231",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004S6wtQQAR",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "Testing",
    "MiddleName": "",
    "LastName": "Testing",
    "Region": "Oakland",
    "SchoolSiteId": "0015000002HvvWDAAZ",
    "SchoolName": "Testing",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2018-11-04",
    "Gender": "Male",
    "Grade": "1st",
    "K12GradeLevel": "",
    "Ethnicity": "Asian",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "Yes",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "Testing",
    "ParentLName": "Testing",
    "ParentEmail": "",
    "Relationship": "Foster Parent",
    "ParentPhone1": "6284440250",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "Bengali",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "Twsting",
    "Emergency_Contact_Relationship": "Foster Parent",
    "Emergency_Contact_Phone1": "6284440250",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  },
  {
    "Id": "0031T00004Sbe1eQAB",
    "ContactType": "SCORES Student",
    "ContactRecordType": "01250000000VBbXAAW",
    "FirstName": "te",
    "MiddleName": "",
    "LastName": "testi",
    "Region": "Oakland",
    "SchoolSiteId": "0015000002HvvWJAAZ",
    "SchoolName": "GFES",
    "PersonalEmail": "",
    "HomePhone": "",
    "Birthdate": "2006-12-06",
    "Gender": "Non-Binary",
    "Grade": "4th",
    "K12GradeLevel": "",
    "Ethnicity": "Hispanic/Latinx",
    "PermissiontoCommuteAlone": "",
    "ReducedPriceLunch": "No",
    "Allergies": "",
    "ExternalStudentId": "",
    "ExternalStudentIdSource": "NONE",
    "ParentFName": "tester",
    "ParentLName": "tester",
    "ParentEmail": "",
    "Relationship": "Parent",
    "ParentPhone1": "4567891231",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "MailingStreet": "",
    "MailingCity": "",
    "MailingState": "",
    "MailingZip": "0",
    "MailingCountry": "US",
    "ParentEnglishFluency": "",
    "ParentHomeLang": "English",
    "OtherLang": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "tester",
    "Emergency_Contact_Relationship": "Legal Guardian",
    "Emergency_Contact_Phone1": "7894564123",
    "Emergency_Contact_Phone2": "",
    "Emergency_Contact_Phone3": "",
    "Emergency_Contact_Permission_to_Pickup_child": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": "",
    "Second_Emergency_Contact_Phone1": "",
    "Second_Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Phone3": "",
    "Second_Emergency_Contact_Permission_to_Pickup_child": "",
    "LiabilityWaiver": "true",
    "MediaReleaseWaiver": "true",
    "DataReleaseWaiver": "true"
  }
])