{
  "searchRecords": [
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0011T00002V6j1OQAR",
        "Email": null,
        "Reduced_Price_Lunch__c": null,
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": null,
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": null,
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": null,
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": null,
        "MailingCity": null,
        "Birthdate": "2011-07-15",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004DO9DVQA1",
        "LastName": "Ariana",
        "School_Attending__c": null,
        "MailingStreet": null,
        "Parent_Phone_01__c": "510-434-6317",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": null,
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": null,
        "Emergency_Contact_Relationship_to_Child__c": null,
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": null,
        "FirstName": "Hernandez Deras",
        "MiddleName": null,
        "External_Student_DB__c": null,
        "Parent_First_Name__c": "Jasmine",
        "Emergency_Contact_Name_Phone_01__c": null,
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": null,
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWCAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": "5107349201",
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": "Mariana Castro-Olivares",
        "Liability__c": "true",
        "Parent_Home_Language__c": "Spanish",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latino",
        "Parent_English_Fluency__c": "Yes",
        "Parent_Last_Name__c": "Gutierrez",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Female",
        "MailingCity": "San Rafael",
        "Birthdate": "2008-04-14",
        "Allergies__c": "none",
        "Parent_Email_Address__c": "deserttransport@yahoo.com",
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T000049b9P7QAI",
        "LastName": "Gutierrez",
        "School_Attending__c": null,
        "MailingStreet": "75 Canal Street Apt. C3",
        "Parent_Phone_01__c": "7602214386",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Parent_Other_Language__c": null,
        "MailingState": "CA",
        "Level__c": null,
        "MailingPostalCode": "94901",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "6th",
        "Emergency_Contact_Relationship_to_Child__c": "Aunt",
        "Parent_Phone_02__c": "4153398813",
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "Ariana",
        "MiddleName": null,
        "External_Student_DB__c": null,
        "Parent_First_Name__c": "Sandra",
        "Emergency_Contact_Name_Phone_01__c": "4155598641",
        "Second_Emerg_Contact_Relationship_Child__c": "Family Friend",
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "Irma del Toro",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWKAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "Data_Release__c": "false",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "false",
        "Parent_Home_Language__c": "Spanish",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latino",
        "Parent_English_Fluency__c": "Yes",
        "Parent_Last_Name__c": "Deras",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Female",
        "MailingCity": "San leandro",
        "Birthdate": "2011-07-15",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00003UDurTQAT",
        "LastName": "Hernandez deras",
        "School_Attending__c": null,
        "MailingStreet": "1575 fir ave",
        "Parent_Phone_01__c": null,
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Parent_Other_Language__c": null,
        "MailingState": "Ca",
        "Level__c": null,
        "MailingPostalCode": "94601",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "3rd",
        "Emergency_Contact_Relationship_to_Child__c": "Father",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "Ariana",
        "MiddleName": null,
        "External_Student_DB__c": "OFCY",
        "Parent_First_Name__c": "Jasmin",
        "Emergency_Contact_Name_Phone_01__c": null,
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "false",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "May Hernandez",
        "External_Student_ID__c": "48818555"
      },
      "searchRecordMetadata": null
    }
  ],
  "queryId": "diy2peey95q4",
  "searchResultsMetadata": null
}