{
  "searchRecords": [
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "San Francisco Crocker"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvVwAAJ",
        "Email": "test@gmail.com",
        "Reduced_Price_Lunch__c": "No",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "Spanish",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latinx",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "test",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Male",
        "MailingCity": null,
        "Birthdate": "2002-10-09",
        "Allergies__c": null,
        "Parent_Email_Address__c": "ignacio.a.lopezscala@gmail.com",
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004RX5a7QAD",
        "LastName": "test",
        "School_Attending__c": "Bridges Academy Elementary School",
        "MailingStreet": null,
        "Parent_Phone_01__c": "7894561231",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "4th",
        "Emergency_Contact_Relationship_to_Child__c": "Legal Guardian",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "test",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "test",
        "Emergency_Contact_Name_Phone_01__c": "7894561231",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "test",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "Oakland"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWQAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "No",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "Chinese (incl. Cantonese, Mandarin, other Chinese languages)",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Caucasian",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "Friend",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Male",
        "MailingCity": null,
        "Birthdate": "2023-04-02",
        "Allergies__c": null,
        "Parent_Email_Address__c": "sdfkhjsdf@sj.com",
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004VBidtQAD",
        "LastName": "test",
        "School_Attending__c": "puffy",
        "MailingStreet": null,
        "Parent_Phone_01__c": "2672626622",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "5th",
        "Emergency_Contact_Relationship_to_Child__c": "Legal Guardian",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Legal Guardian",
        "FirstName": "test",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "Friendly",
        "Emergency_Contact_Name_Phone_01__c": "3434343434",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "refriend friend",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "Oakland"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWRAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": "Yes",
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "English",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latinx",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "test12",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Male",
        "MailingCity": null,
        "Birthdate": "2011-12-29",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004S5yN4QAJ",
        "LastName": "test",
        "School_Attending__c": "MLK",
        "MailingStreet": null,
        "Parent_Phone_01__c": "4155325763",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "3rd",
        "Emergency_Contact_Relationship_to_Child__c": "Grandparent",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "test",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "test 12",
        "Emergency_Contact_Name_Phone_01__c": "4152525252",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "test",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "Hayward"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWaAAJ",
        "Email": null,
        "Reduced_Price_Lunch__c": "No",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "Spanish",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latinx",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "User test",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Non-Binary",
        "MailingCity": null,
        "Birthdate": "2009-02-10",
        "Allergies__c": null,
        "Parent_Email_Address__c": "testing@gmail.com",
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004TxcXuQAJ",
        "LastName": "testing",
        "School_Attending__c": "Bret",
        "MailingStreet": null,
        "Parent_Phone_01__c": "4155555555",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "4th",
        "Emergency_Contact_Relationship_to_Child__c": "Grandparent",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "User test",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "User test",
        "Emergency_Contact_Name_Phone_01__c": "4155555555",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "User test",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": null
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0011T00002lM2T9QAK",
        "Email": "test009@scores.org",
        "Reduced_Price_Lunch__c": null,
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": null,
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": null,
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": null,
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": null,
        "MailingCity": null,
        "Birthdate": null,
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004UMvefQAD",
        "LastName": "Test009",
        "School_Attending__c": "Civic Center",
        "MailingStreet": null,
        "Parent_Phone_01__c": null,
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": null,
        "RecordTypeId": "01250000000VAMzAAO",
        "Grade__c": null,
        "Emergency_Contact_Relationship_to_Child__c": null,
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": null,
        "FirstName": "Student009",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": null,
        "Emergency_Contact_Name_Phone_01__c": null,
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": null,
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "San Francisco Civic Center"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvW3AAJ",
        "Email": null,
        "Reduced_Price_Lunch__c": "No",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": "No",
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "English",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latinx",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "testingModal",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Unknown",
        "MailingCity": null,
        "Birthdate": "2011-10-26",
        "Allergies__c": null,
        "Parent_Email_Address__c": "testing@hotmail.com",
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004S5LKCQA3",
        "LastName": "testingModa",
        "School_Attending__c": "John",
        "MailingStreet": null,
        "Parent_Phone_01__c": "4155551234",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "3rd",
        "Emergency_Contact_Relationship_to_Child__c": "Legal Guardian",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "testingModa",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "testingModal",
        "Emergency_Contact_Name_Phone_01__c": "7894561231",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "testingModal",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "Oakland"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWDAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "Yes",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "Bengali",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Asian",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "Testing",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Male",
        "MailingCity": null,
        "Birthdate": "2018-11-04",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004S6wtQQAR",
        "LastName": "Testing",
        "School_Attending__c": "Testing",
        "MailingStreet": null,
        "Parent_Phone_01__c": "6284440250",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "1st",
        "Emergency_Contact_Relationship_to_Child__c": "Foster Parent",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Foster Parent",
        "FirstName": "Testing",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "Testing",
        "Emergency_Contact_Name_Phone_01__c": "6284440250",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "Twsting",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Account": {
          "Id": null,
          "type": "Account",
          "Region__c": "Oakland"
        },
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvWJAAZ",
        "Email": null,
        "Reduced_Price_Lunch__c": "No",
        "type": "Contact",
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "Second_Emergency_Phone_01__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Permission_to_Pick_Up__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Liability__c": "true",
        "Parent_Home_Language__c": "English",
        "Second_Emergency_Phone_02__c": null,
        "Ethnicity__c": "Hispanic/Latinx",
        "Parent_English_Fluency__c": null,
        "Parent_Last_Name__c": "tester",
        "Second_Emergency_Permission_to_Pick_Up__c": null,
        "Gender__c": "Non-Binary",
        "MailingCity": null,
        "Birthdate": "2006-12-06",
        "Allergies__c": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name_Phone_03__c": null,
        "Id": "0031T00004Sbe1eQAB",
        "LastName": "testi",
        "School_Attending__c": "GFES",
        "MailingStreet": null,
        "Parent_Phone_01__c": "4567891231",
        "Second_Emergency_Phone_03__c": null,
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": "US",
        "Parent_Other_Language__c": null,
        "MailingState": null,
        "Level__c": null,
        "MailingPostalCode": "0",
        "RecordTypeId": "01250000000VBbXAAW",
        "Grade__c": "4th",
        "Emergency_Contact_Relationship_to_Child__c": "Legal Guardian",
        "Parent_Phone_02__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": "Parent",
        "FirstName": "te",
        "MiddleName": null,
        "External_Student_DB__c": "NONE",
        "Parent_First_Name__c": "tester",
        "Emergency_Contact_Name_Phone_01__c": "7894564123",
        "Second_Emerg_Contact_Relationship_Child__c": null,
        "Media_Release__c": "true",
        "HomePhone": null,
        "Emergency_Contact_Name__c": "tester",
        "External_Student_ID__c": null
      },
      "searchRecordMetadata": null
    }
  ],
  "queryId": "g7f82696zgj4",
  "searchResultsMetadata": null
}