#%RAML 1.0 NamedExample
assessment-get-examples:
    {
      "Id": "a0k53000000IMIiAAO",
      "FirstName": "Test",
      "LastName": "StudentTest Student 0011",
      "AssessmentResponse": "3",
      "AssessmentType": "PACER",
      "StudentId": "0031T00004EjgC8QAJ",
      "SessionId": "a0p530000000B18AAE",
      "LastModified": "2022-01-23"
    }
  