#%RAML 1.0 Library

types:
  Season:
    type: object
    description: Season Salesforce object
    properties:
      Id: 
        type: SalesforceUniqueId
      Name:
        type: string
      StartDate:
        type: date-only
      EndDate:
        type: date-only  
  Team:
    type: object
    description: Team Salesforce object
    properties:
      TeamName:
        type: string
      TeamId:
        type: SalesforceUniqueId
      AccountName:
        type: string
      AccountId:
        type: SalesforceUniqueId
  
  TeamCreateModel:
    type: object
    description: Team object for POST endpoint
    properties:
      TeamName:
        type: string
      ScoresProgramType:
        type: string
        required: false
      ProgramSite:
        type: string
        required: false
      CoachSoccer:
        type: SalesforceUniqueId
        required: false
      CoachWriting:
        type: SalesforceUniqueId
        required: false
      ScoresProgramCoordinator:
        type: SalesforceUniqueId
        required: false
      ScoresProgramManager:
        type: SalesforceUniqueId
        required: false
  
  TeamUpdateModel:
    type: object
    description: Team object for PATCH endpoint
    properties:
      TeamName:
        type: string
        required: false
      ScoresProgramType:
        type: string
        required: false
      ProgramSite:
        type: string
        required: false
      CoachSoccer:
        type: SalesforceUniqueId
        required: false
      CoachWriting:
        type: SalesforceUniqueId
        required: false
      ScoresProgramCoordinator:
        type: SalesforceUniqueId
        required: false
      ScoresProgramManager:
        type: SalesforceUniqueId
        required: false
      
  TeamSeasonBaseModel: 
    type: object
    description: Team Season Salesforce object
    properties:
      TeamSeasonName:
        type: string
      TeamSeasonId:
        type: SalesforceUniqueId
      TeamName:
        type: string
      SeasonName:
        type: string
      SchoolSite:
        type: string
      Partnership:
        type: string
      TotalNoOfPlayers:
        type: number
      TotalNoOfSessions:
        type: number
      SeasonStartDate:
        type: date-only
      SeasonEndDate:
        type: date-only
      CoachSoccer:
        type: SalesforceUniqueId
      CoachWriting:
        type: SalesforceUniqueId
      ProgramCoordinator:
        type: SalesforceUniqueId
      ScoresProgramManager:
        type: SalesforceUniqueId
      Region:
        type: string
        required: false
      SessionId:
        type: SalesforceUniqueId
        required: false
    examples: !include teamseason-base-examples.raml
      
  TeamSeason:
    type: TeamSeasonBaseModel
    properties:
      Season_Name:
        type: string
        required: false
      Team_Name:
        type: string
        required: false
      Sessions:
        type: array
        required: false
        items:
          type: Session
      Enrollments:
        type: array
        required: false
        items:
          type: Enrollment
    examples: !include teamseason-full-examples.raml
  Session:
    type: object
    description: Session of a team season
    properties:
      SessionId:
        type: SalesforceUniqueId
      SessionName:
        type: string
      SessionDate:
        type: date-only
      SessionTopic:
        type: string
        enum: [ "Soccer", "Writing", "Game_Day", "Soccer_and_Writing"]
      TeamSeasonId:
        type: SalesforceUniqueId
      AttendanceList:
        type: array
        required: false
        items:
          type: AttendanceUpdateModel
    examples: !include session-examples.raml

  TeamSeasonCreateModel:
    type: object
    description: TeamSeason object for POST endpoint
    properties:
      TeamSeasonName:
        type: string
      TeamId:
        type: SalesforceUniqueId
      SeasonId:
        type: SalesforceUniqueId
      SchoolSite:
        type: string
        required: false
      Partnership:
        type: string
        required: false
      TotalNoOfPlayers:
        type: number
        required: false
      TotalNoOfSessions:
        type: number
        required: false
      SeasonStartDate:
        type: date-only
        required: false
      SeasonEndDate:
        type: date-only
        required: false
      CoachSoccer:
        type: SalesforceUniqueId
        required: false
      CoachWriting:
        type: SalesforceUniqueId
        required: false

  TeamSeasonUpdateModel:
    type: object
    description: TeamSeason object for PATCH endpoint
    properties:
      TeamSeasonName:
        type: string
        required: false
      TeamId:
        type: SalesforceUniqueId
        required: false
      SeasonId:
        type: SalesforceUniqueId
        required: false
      SchoolSite:
        type: string
        required: false
      Partnership:
        type: string
        required: false
      TotalNoOfPlayers:
        type: number
        required: false
      TotalNoOfSessions:
        type: number
        required: false
      SeasonStartDate:
        type: date-only
        required: false
      SeasonEndDate:
        type: date-only
        required: false
      CoachSoccer:
        type: SalesforceUniqueId
        required: false
      CoachWriting:
        type: SalesforceUniqueId
        required: false
      ProgramCoordinator:
        type: SalesforceUniqueId
        required: false
      ProgramManager:
        type: SalesforceUniqueId
        required: false

  SessionCreateModel:
    type: object
    description: Session of a team season
    properties:
      SessionDate:
        type: date-only
      SessionTopic:
        type: string
        enum: [ "Soccer", "Writing", "Game Day", "Soccer and Writing", "Service Learning"]
      TeamSeasonId:
        type: SalesforceUniqueId
    examples: !include sessioncreatemodel-examples.raml

  SessionUpdateModel:
    type: object
    description: Session object for a PATCH endpoint
    properties:
      SessionName:
        type: string
        required: false
      SessionDate:
        type: date-only
        required: false
      SessionTopic:
        type: string
        enum: [ "Soccer", "Writing", "Game Day", "Soccer and Writing", "Service Learning"]
        required: false
      TeamSeasonId:
        type: SalesforceUniqueId
        required: false
      Headcount:
        type: number
        required: false
      FemaleHeadcount:
        type: number
        required: false

  AttendanceCreateModel:
    type: object
    properties:
      SessionId:
        type: SalesforceUniqueId
      StudentId:
        type: SalesforceUniqueId
      Attended:
        type: boolean
  
  AttendanceUpdateModel:
    type: AttendanceBaseModel
    description: Attendance object for updating an attendance for a session
    properties:
      AttendanceId:
        type: SalesforceUniqueId
        required: false
      AttendanceName:
        type: string
        required: false
  AttendanceBaseModel:
    type: object
    description: Attendance of a session
    properties:
      SessionId:
        type: SalesforceUniqueId
        required: false
      SessionName:
        type: string
        required: false
      StudentId:
        type: SalesforceUniqueId
        required: false
      StudentName:
        type: string
        required: false
      RecordType:
        type: string
        required: false
      RecordedDate:
        type: date-only
        required: false
      Attended:
        type: boolean
    examples: !include attendance-examples.raml
  
  Enrollment:
    type: object
    description: Enrollement of a session
    properties:
      EnrollmentId:
        type: SalesforceUniqueId
      EnrollmentName:
        type: string
      SessionId:
        type: SalesforceUniqueId
      SessionName:
        type: string
      StudentId:
        type: SalesforceUniqueId
      FirstName:
        type: string
      LastName:
        type: string
      Birthdate:
        type: string
      Gender:
        type: string
      Ethnicity:
        type: string
      ZipCode:
        type: string
      StudentRecordComplete:
        type: boolean
      RecordType:
        type: string
      Date:
        type: date-only
      Attended:
        type: boolean
    examples: !include enrollment-examples.raml

  EnrollmentByContactID:
    type: object
    description: Enrollment data structure
    properties:
      Id: string
      TeamSeasonId: string
      TeamSeasonName: string
      StartDate: date-only
      EndDate: date-only
      SeasonName: string
      TeamID: string
      TeamName: string
      SchoolSiteId: string
      SchoolSiteName: string

  EnrollmentCreateModel:
    type: object
    description: Enrollement object for a POST endpoint
    properties:
      TeamSeasonId:
        type: SalesforceUniqueId
      StudentId:
        type: SalesforceUniqueId
      StartDate:
        type: date-only
        required: false
      EndDate: 
        type: date-only
        required: false

  EnrollmentUpdateModel:
    type: object
    description: Enrollement object for a PATCH endpoint
    properties:
      TeamSeasonId:
        type: SalesforceUniqueId
        required: false
      StudentId:
        type: SalesforceUniqueId
        required: false
      StartDate:
        type: date-only
        required: false
      EndDate: 
        type: date-only
        required: false
  EnrollmentUpdateModelDatesOnly:
    type: object
    description: Enrollement object for a PATCH endpoint
    properties:
      StartDate:
        type: date-only
        required: false
      EndDate: 
        type: date-only
        required: false

  SalesforceUniqueId:
    displayName: SalesforceUniqueId
    description: Unique Id of an object in Salesforce
    type: string
    maxLength: 18


  Contact:
    type: object
    description: Salesforce Contact Object
    properties:
      Id:
        type: SalesforceUniqueId
        required: false
      ContactType:
        type: string
        enum: [ "SCORES Student"]
        required: false
      ContactRecordType: 
        type: string
        required: false
      FirstName:
        type: string
      MiddleName:
        type: string
        required: false
      LastName:
        type: string
      SchoolName:
        type: string
        required: false
      SchoolSiteId:
        type: SalesforceUniqueId
        required: false 
      PersonalEmail:
        type: string
        required: false
      HomePhone:
        type: string
        required: false
      Birthdate:
        type: date-only
        required: false
      Gender: 
        type: string
        required: false
      Grade:
        type: string
        required: false
      K12GradeLevel:
        type: string
        required: false
      Ethnicity: 
        type: string
        required: false
      ReducedPriceLunch:
        type: string
        required: false
      Allergies: 
        type: string
        required: false
      PermissiontoCommuteAlone:
        type: string
        required: false
      ExternalStudentId:
        type: string
        required: false
      ExternalStudentIdSource:
        type: string
        required: false
      ParentFName:
        type: string
        required: false
      ParentLName:
        type: string
        required: false
      ParentEmail:
        type: string
        required: false
      Relationship:
        type: string
        required: false
      ParentPhone1:
        type: string
        required: false
      ParentPhone2:
        type: string
        required: false
      ParentPhone3:
        type: string
        required: false
      MailingStreet:
        type: string
        required: false
      MailingCity:
        type: string
        required: false
      MailingState:
        type: string
        required: false
      MailingZip:
        type: string
        required: false
      MailingCountry:
        type: string
        required: false
      ParentEnglishFluency:
        type: string
        required: false
      ParentHomeLang:
        type: string
        required: false
      OtherLang:
        type: string
        required: false
      Volunteer:
        type: string
        required: false
      Emergency_Contact_Name:
        type: string
        required: false
      Emergency_Contact_Relationship:
        type: string
        required: false
      Emergency_Contact_Phone1:
        type: string
        required: false
      Emergency_Contact_Phone2:
        type: string
        required: false
      Emergency_Contact_Phone3:
        type: string   
        required: false 
      Emergency_Contact_Permission_to_Pickup_child:
        type: string
        required: false
      Second_Emergency_Contact_Name:
        type: string
        required: false
      Second_Emergency_Contact_Relationship:
        type: string
        required: false
      Second_Emergency_Contact_Phone1:
        type: string
        required: false
      Second_Emergency_Contact_Phone2:
        type: string
        required: false
      Second_Emergency_Contact_Phone3:
        type: string
        required: false 
      Second_Emergency_Contact_Permission_to_Pickup_child:
        type: string
        required: false
      LiabilityWaiver:
         type: boolean
         required: false
      DataReleaseWaiver:
       type: boolean
       required: false
      MediaReleaseWaiver:
       type: boolean
       required: false
      LatestEnrolledEndDate:
        type: date-only
        required: false
      LatestEnrolledSiteId:
        type: string
        required: false
      LatestEnrolledSiteName:
        type: string
        required: false

  ContactPatchModel:
    type: object
    description: Salesforce Contact Object with all fields optional
    properties:
      FirstName:
        type: string
        required: false
      MiddleName:
        type: string
        required: false
      LastName:
        type: string
        required: false
      PersonalEmail:
        type: string
        required: false
      HomePhone:
        type: string
        required: false
      Birthdate:
        type: date-only
        required: false
      Gender: 
        type: string
        required: false
      Grade:
        type: string
        required: false
      Ethnicity: 
        type: string
        required: false
      ReducedPriceLunch:
        type: string
        required: false
      Allergies: 
        type: string
        required: false
      PermissiontoCommuteAlone:
        type: string
        required: false
      ExternalStudentId:
        type: string
        required: false
      ExternalStudentIdSource:
        type: string
        required: false
      ParentFName:
        type: string
        required: false
      ParentLName:
        type: string
        required: false
      ParentEmail:
        type: string
        required: false
      Relationship:
        type: string
        required: false
      ParentPhone1:
        type: string
        required: false
      ParentPhone2:
        type: string
        required: false
      ParentPhone3:
        type: string
        required: false
      MailingStreet:
        type: string
        required: false
      MailingCity:
        type: string
        required: false
      MailingState:
        type: string
        required: false
      MailingZip:
        type: string
        required: false
      MailingCountry:
        type: string
        required: false
      ParentEnglishFluency:
        type: string
        required: false
      ParentHomeLang:
        type: string
        required: false
      OtherLang:
        type: string
        required: false
      Volunteer:
        type: string
        required: false
      Emergency_Contact_Name:
        type: string
        required: false
      Emergency_Contact_Relationship:
        type: string
        required: false
      Emergency_Contact_Phone1:
        type: string
        required: false
      Emergency_Contact_Phone2:
        type: string
        required: false
      Emergency_Contact_Phone3:
        type: string    
        required: false
      Emergency_Contact_Permission_to_Pickup_child:
        type: string
        required: false
      Second_Emergency_Contact_Name:
        type: string
        required: false
      Second_Emergency_Contact_Relationship:
        type: string
        required: false
      Second_Emergency_Contact_Phone1:
        type: string
        required: false
      Second_Emergency_Contact_Phone2:
        type: string
        required: false
      Second_Emergency_Contact_Phone3:
        type: string    
        required: false
      Second_Emergency_Contact_Permission_to_Pickup_child:
        type: string
        required: false
      LiabilityWaiver:
        type: boolean
        required: false
      DataReleaseWaiver:
        type: boolean
        required: false
      MediaReleaseWaiver:
        type: boolean
        required: false

  SchoolSite:
    type: object
    description: Salesforce Account Object of type SchoolSite
    properties:
      Id:
        type: SalesforceUniqueId
      Name:
        type: string
  
  Assessment:
    type: object
    description: Assessment abstract type, metrics, feedback
    properties:
      Id:
        type: SalesforceUniqueId
      FirstName:
        type: string
      LastName:
        type: string
      AssessmentResponse:
        type: string
      LastModified:
        type: date-only
      AssessmentType:
        type: string
      SessionId:
        type: SalesforceUniqueId
      StudentId:
        type: SalesforceUniqueId
    examples: !include assessment-get-examples.raml

  AssessmentCreateModel:
    type: object
    description: create new assessment record
    properties:
      StudentId:
        type: SalesforceUniqueId
        required: true
      AssessmentResponse:
        type: string
        required: true
      AssessmentType:
        type: string
        required: true
        enum: [ "PACER","Activity_Feedback"]
    examples: !include assessment-post-example.raml

  AssessmentUpdateModel:
    type: object
    description: Assessment object for updating an attendance for a session
    properties:
      AssessmentId:
        type: SalesforceUniqueId
        required: true
      AssessmentResponse:
        type: string
        required: true
    examples: !include assessments-patch-example.raml
  
  UserAccount:
    type: object
    properties:
      MatchFound:
        type: boolean
      UserType:
        type: string
        enum: ["Coach", "Parent", "Other"]
      CoachId:
        type: SalesforceUniqueId
        required: false
      ParentFName:
        type: string
        required: false
      ParentLName:
        type: string
        required: false
        
  WaiverHistory:
    type: object
    properties:
      WaiverHistoryId:
        type: SalesforceUniqueId
      Name:
        type: string
      WaiverId:
        type: SalesforceUniqueId
      PaperReceived:
        type: boolean
      ContactId:
        type: SalesforceUniqueId
      ContactEmail:
        type: string
      PaperReceivedDate:
        type: date-only
      WaiverCreatedDate:
        type: date-only
  SCORES_Task:
    type: object
    properties:
      Id: string
      AssignedBy: string
      AssignedTo: string
      CreatedBy: string
      CreatedContact: string
      Description: string
      DueDate: datetime
      LastModifiedBy: string
      LastModifiedContact: string
      OwnerId: string
      Priority: number
      PriorityIcon: string
      ResourceLink: string
      Session: string
      Name: string
      TaskStatus: string
      TaskType: string
  SCORES_Task_Create:
    type: object
    properties:
      AssignedBy: 
        type: string
        required: false    
      AssignedTo: 
        type: string
        required: true
      CreatedByContact: 
        type: string
        required: false
      Description:
        type: string
        required: false
      DueDate:
        type: datetime
        required: false
      LastModifiedBy:
        type: string
        required: false
      Name: 
        type: string
        required: false
      OwnerId:
        type: string
        required: false
      Priority: 
        type: number
        required: false
      ResourceLink: 
        type: string
        required: false
      Session: 
        type: string
        required: false
      TaskType: 
        type: string
        required: false 
  SCORES_Tag:
    type: object
    properties:
      Id: string
      TaskId: string
      TaskName: string
      TagId: string
      TagName: string
      TagColor: string
      Description: string
      TaskTagName: string
