#%RAML 1.0 NamedExample
enrollment-examples:
  {
    "EnrollmentId": "a0l3F000004ZYhWQAW",
    "EnrollmentName": "A-114946",
    "Attended": true,
    "RecordType": "SCORES Contact",
    "SessionId": "a0p1T00000IGus3QAD",
    "SessionName": "S-123456",
    "StudentId": "0035000002vTwcyAAC",
    "FirstName": "Kari Melissa",
    "LastName": "Gomez Soliz",
    "Birthdate": "2009-01-01",
    "Gender": "Female",
    "Ethnicity": "Hispanic/Latino",
    "ZipCode": "94601",
    "Date": "2019-08-23"
  }