#%RAML 1.0 NamedExample
sessioncreatemodel-examples:
  {
    "SessionDate": "2019-08-23",
    "SessionTopic": "Soccer",
    "TeamSeasonId": "a0q1T000008Jt3NQAS",
    "Headcount":"10",
    "FemaleHeadcount":"5"
  }