#%RAML 1.0 NamedExample
session-examples:
  {
    "SessionDate": "2019-08-23",
    "SessionId": "a0p1T00000IGus3QAD",
    "SessionName": "S-123456",
    "SessionTopic": "Soccer",
    "TeamSeasonId": "a0q1T000008Jt3NQAS",
    "Headcount":"10",
    "FemaleHeadcount":"5",
    "AttendanceList": [
        {
          "AttendanceId": "a0l3F000004ZYhWQAW",
          "AttendanceName": "A-114946",
          "SessionId": "a0p1T00000IGus3QAD",
          "SessionName": "S-123456",
          "StudentId": "0035000002vTwcyAAC",
          "StudentName": "Joe Smith",
          "RecordType": "SCORES Contact",
          "RecordedDate": "2019-08-23",
          "Attended": true
        }
    ]
  }