#%RAML 1.0 NamedExample
teamseason-examples:
  {
    "TeamSeasonId": "a0q1T000008Jt3NQAS",
    "TeamSeasonName": "ASCEND Boys-2019 Fall",
    "Partnership": "a0n1T00000NSoeeQAD",
    "SchoolSite": "ASCEND Elementary School",
    "SeasonStartDate": "2019-12-20",
    "SeasonEndDate": "2019-08-12",
    "SeasonName": "a0o1T000005CitnQAC",
    "TeamName": "a1N1T000005wKT8UAM",
    "TotalNoOfPlayers": 12,
    "TotalNoOfSessions": 38,
    "CoachSoccer": "0031T00003OcljGQAR",
    "CoachWriting": "0031T00003OcljGQAR",
    "ScoresProgramManager": "Pete-Coach Tester",
    "ProgramCoordinator": "Pete-Coach Tester",
    "Region": "Oakland",
    "SeasonId": "a0o1T000005n5TmQAI"
  }