#%RAML 1.0 NamedExample
teamseason-examples:
  {
    "TeamSeasonId": "a0q1T000008Jt3NQAS",
    "TeamSeasonName": "ASCEND Boys-2019 Fall",
    "Partnership": "a0n1T00000NSoeeQAD",
    "SchoolSite": "ASCEND Elementary School",
    "SeasonStartDate": "2019-12-20",
    "SeasonEndDate": "2019-08-12",
    "SeasonName": "a0o1T000005CitnQAC",
    "TeamName": "a1N1T000005wKT8UAM",
    "TotalNoOfPlayers": 12,
    "TotalNoOfSessions": 38,
    "CoachSoccer": "0031T00003OcljGQAR",
    "CoachWriting": "0031T00003OcljGQAR",
    "ScoresProgramManager": "0031T00003OcljGQAR",
    "ProgramCoordinator": "0031T00003OcljGQAR",
    "Team_Name" : "ASCEND Boys",
    "Season_Name": "2019 Fall",
    "Sessions": [
      {
        "SessionDate": "2019-08-23",
        "SessionId": "a0p1T00000IGus3QAD",
        "SessionName": "S-123456",
        "SessionTopic": "Soccer",
        "TeamSeasonId": "a0q1T000008Jt3NQAS"
      }
    ],
    "Enrollments": [
      {
        "EnrollmentId": "a0l3F000004ZYhWQAW",
        "EnrollmentName": "A-114946",
        "Attended": true,
        "RecordType": "SCORES Contact",
        "SessionId": "a0p1T00000IGus3QAD",
        "SessionName": "S-123456",
        "StudentId": "0035000002vTwcyAAC",
        "FirstName": "Kari Melissa",
        "LastName": "Gomez Soliz",
        "Birthdate": "2009-01-01",
        "Gender": "Female",
        "StudentRecordComplete": false,
        "Ethnicity": "Hispanic/Latino",
        "ZipCode": "94601",
        "Date": "2019-08-23",
        "Dropped": false,
        "DropReason": ""
      }
    ]
  }