{
  "headers": {
    "host": "localhost:8091",
    "connection": "keep-alive",
    "content-length": "1306",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "http://localhost:8091",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8091/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api-internal/contact",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/contact",
  "listenerPath": "/api-internal/*",
  "localAddress": "/127.0.0.1:8091",
  "relativePath": "/api-internal/contact",
  "uriParams": {},
  "rawRequestUri": "/api-internal/contact",
  "rawRequestPath": "/api-internal/contact",
  "remoteAddress": "/127.0.0.1:56258",
  "requestPath": "/api-internal/contact"
}