# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull Request Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add repo credentials
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: |
          [{
           "id": "mule-enterprise",
           "username": "${{ secrets.MULE_NEXUS_USERNAME }}",
           "password": "${{ secrets.MULE_NEXUS_PASSWORD }}"
          },
          {
           "id": "scores-exchange",
           "username": "${{ secrets.ANYPOINT_CICD_USERNAME }}",
           "password": "${{ secrets.ANYPOINT_CICD_PASSWORD }}"
          }]
    - name: Print effective-settings
      run: mvn help:effective-settings
    - name: Build with Maven
      run: mvn -B package --file pom.xml
