%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Id": "0031T00004CZca4QAD",
    "FirstName": "Alexander",
    "MiddleName": "",
    "LastName": "Puz Delton",
    "Name": "Alexander Puz Delton",
    "DateOfBirth": "2010-09-07",
    "Grade": "",
    "StreetAddress": "",
    "City": "",
    "State": "",
    "Zip": "",
    "Country": "",
    "HomePhone": "",
    "Email": "",
    "HomeLanguage": "",
    "Ethnicity": "",
    "Gender": "",
    "Allergies": "",
    "SchoolAttending": "",
    "K12GradeLevel": "",
    "SchoolSiteId": "0015000002HvvVxAAJ",
    "DataReleaseWaiver": "true",
    "ParentFName": "Doris",
    "ParentLName": "Lalila Siquinajay",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "510-395-3624",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "ReducedPriceLunch": "",
    "PermissiontoCommuteAlone": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": ""
  },
  {
    "Id": "0031T00004CZcaDQAT",
    "FirstName": "Edgar Cayetano",
    "MiddleName": "",
    "LastName": "Puz",
    "Name": "Edgar Cayetano Puz",
    "DateOfBirth": "2009-07-02",
    "Grade": "",
    "StreetAddress": "",
    "City": "",
    "State": "",
    "Zip": "",
    "Country": "",
    "HomePhone": "",
    "Email": "",
    "HomeLanguage": "",
    "Ethnicity": "",
    "Gender": "",
    "Allergies": "",
    "SchoolAttending": "",
    "K12GradeLevel": "",
    "SchoolSiteId": "0015000002HvvVxAAJ",
    "DataReleaseWaiver": "true",
    "ParentFName": "Doris",
    "ParentLName": "Lalila Siquinajay",
    "ParentEmail": "",
    "Relationship": "",
    "ParentPhone1": "510-395-3624",
    "ParentPhone2": "",
    "ParentPhone3": "",
    "ReducedPriceLunch": "",
    "PermissiontoCommuteAlone": "",
    "Volunteer": "",
    "Emergency_Contact_Name": "",
    "Emergency_Contact_Relationship": "",
    "Emergency_Contact_Phone1": "",
    "Emergency_Contact_Phone2": "",
    "Second_Emergency_Contact_Name": "",
    "Second_Emergency_Contact_Relationship": ""
  }
])