{
  "searchRecords": [
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvVxAAJ",
        "Email": null,
        "Parent_Phone_01__c": "510-395-3624",
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Reduced_Price_Lunch__c": null,
        "type": "Contact",
        "MailingState": null,
        "Name": "Alexander Puz Delton",
        "Level__c": null,
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "MailingPostalCode": null,
        "RecordTypeId": "01250000000VBbXAAW",
        "Zip_First_Five_Digits__c": null,
        "Grade__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Relationship_to_Child__c": null,
        "Parent_Phone_02__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": null,
        "FirstName": "Alexander",
        "Parent_Home_Language__c": null,
        "Ethnicity__c": null,
        "Parent_Last_Name__c": "Lalila Siquinajay",
        "Gender__c": null,
        "MailingAddress": null,
        "MailingCity": null,
        "MiddleName": null,
        "Birthdate": "2010-09-07",
        "Parent_First_Name__c": "Doris",
        "Allergies__c": null,
        "Emergency_Contact_Name_Phone_01__c": null,
        "HomePhone": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name__c": null,
        "External_Student_ID__c": null,
        "Id": "0031T00004CZca4QAD",
        "LastName": "Puz Delton",
        "School_Attending__c": null,
        "MailingStreet": null
      },
      "searchRecordMetadata": null
    },
    {
      "snippet": null,
      "record": {
        "Parent_Phone_03__c": null,
        "AccountId": "0015000002HvvVxAAJ",
        "Email": null,
        "Parent_Phone_01__c": "510-395-3624",
        "Contact_Type__c": "SCORES Student",
        "MailingCountry": null,
        "Reduced_Price_Lunch__c": null,
        "type": "Contact",
        "MailingState": null,
        "Name": "Edgar Cayetano Puz",
        "Level__c": null,
        "Data_Release__c": "true",
        "Emergency_Contact_Name_Phone_02__c": null,
        "MailingPostalCode": null,
        "RecordTypeId": "01250000000VBbXAAW",
        "Zip_First_Five_Digits__c": null,
        "Grade__c": null,
        "Volunteer_for_this_Program_Parent__c": null,
        "Emergency_Contact_Relationship_to_Child__c": null,
        "Parent_Phone_02__c": null,
        "Second_Emergency_Contact_Name__c": null,
        "Permission_to_Commute_Alone__c": null,
        "Parent_Relationship_to_Child__c": null,
        "FirstName": "Edgar Cayetano",
        "Parent_Home_Language__c": null,
        "Ethnicity__c": null,
        "Parent_Last_Name__c": "Lalila Siquinajay",
        "Gender__c": null,
        "MailingAddress": null,
        "MailingCity": null,
        "MiddleName": null,
        "Birthdate": "2009-07-02",
        "Parent_First_Name__c": "Doris",
        "Allergies__c": null,
        "Emergency_Contact_Name_Phone_01__c": null,
        "HomePhone": null,
        "Parent_Email_Address__c": null,
        "Emergency_Contact_Name__c": null,
        "External_Student_ID__c": null,
        "Id": "0031T00004CZcaDQAT",
        "LastName": "Puz",
        "School_Attending__c": null,
        "MailingStreet": null
      },
      "searchRecordMetadata": null
    }
  ],
  "queryId": "-h27kmgfm6x4k",
  "searchResultsMetadata": null
}